management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,env

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${ru.otus.otuskotlin.desksharing.auth.keycloack.clientId}
            authorization-grant-type: ${ru.otus.otuskotlin.desksharing.auth.keycloack.authorizationGrantType}
            scope: ${ru.otus.otuskotlin.desksharing.auth.keycloack.scope}
        provider:
          keycloak:
            issuer-uri: ${ru.otus.otuskotlin.desksharing.auth.keycloack.issuerUri}
            user-name-attribute: ${ru.otus.otuskotlin.desksharing.auth.keycloack.userNameAttribute}
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - name: v1
        url: specification-demand-v1.yaml

ru:
  otus:
    otuskotlin:
      desksharing:
        auth:
          keycloack:
            clientId: desk-sharing
            authorizationGrantType: authorization_code
            scope: openid
            issuerUri: http://localhost:8081/auth/realms/DemandRealm
            userNameAttribute: preferred_username
